version: "3.8"
services:
  node-docker-test:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-docker-test
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - postgres
  vue_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - 8080:8080
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5438"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sq
